name: Scyclone

on:
  workflow_dispatch: # lets you run a build from github.com
  push:
    branches: [ develop]

jobs:
  cmake-build:
    name: CMake Build
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: echo "Hello World"